name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6

      - name: Create archive
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: webclip-${{ steps.extract_version.outputs.version }}.zip
          directory: 'build'

      - name: Save zip
        uses: actions/upload-artifact@v2
        with:
          name: zip
          path: build/webclip-${{ steps.extract_version.outputs.version }}.zip
          retention-days: 30

  pre-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: zip

      - name: Create pre-release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.build.outputs.version }}-dev
          commit: ${{ github.sha }}
          prerelease: true
          allowUpdates: true
          artifacts: "*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs:
      - build
      - pre-release
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: zip

      - name: Create draft release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.build.outputs.version }}
          commit: ${{ github.sha }}
          allowUpdates: false
          artifacts: "*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}